[package]
name = "immermemo-sync"
version.workspace = true
edition.workspace = true

[dependencies]
immermemo-identity = { workspace = true }
immermemo-merge = { workspace = true }
immermemo-vault = { workspace = true }

#= Tomet
tomet = { workspace = true, features = ["parser", "printer"] }

#= Crates.io
anyhow = { workspace = true }
git2 = { workspace = true }
openssl = { workspace = true }

[dev-dependencies]
tempfile = "3"
