[package]
name = "immermemo-editor"
version.workspace = true
edition.workspace = true

[dependencies]
immermemo-index = { workspace = true }
immermemo-merge = { workspace = true }
immermemo-sync = { workspace = true }
immermemo-vault = { workspace = true }

#= Tomet
tomet-ast = { workspace = true }
tomet-parser = { workspace = true }
tomet-printer = { workspace = true }
tomet-stats = { workspace = true }

#= Crates.io
loro = { workspace = true }

[dev-dependencies]
immermemo-tomet-render = { workspace = true }
