[package]
name = "immermemo-editor"
version.workspace = true
edition.workspace = true

[dependencies]
immermemo-identity = { workspace = true }
immermemo-index = { workspace = true }
immermemo-merge = { workspace = true }
immermemo-sync = { workspace = true }
immermemo-vault = { workspace = true }

#= Tomet
tomet = { workspace = true, features = ["edit", "parser", "printer", "stats"] }

#= Crates.io
loro = { workspace = true }

[dev-dependencies]
immermemo-tomet-render = { workspace = true }
anyhow = { workspace = true }
git2 = { workspace = true }
tempfile = "3"
